version: "3"
services:
  manager:
    build:
      context: "./manager"
      dockerfile: "Dockerfile"
    ports:
      - 8000:80
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "database"
      CSV_FILENAME: "data.csv"

    depends_on:
      - db
    
  db:
    image: "postgres"
    ports:
      - "8001:5432"
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "database"
      CSV_FILENAME: "data.csv"
      










